// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/BentoGrid.tsx": () => import("../components/mockups/dashboard-layouts/BentoGrid.tsx"),
  "./components/mockups/dashboard-layouts/CleanMinimal.tsx": () => import("../components/mockups/dashboard-layouts/CleanMinimal.tsx"),
  "./components/mockups/dashboard-layouts/DarkCommand.tsx": () => import("../components/mockups/dashboard-layouts/DarkCommand.tsx")
};
